### ISSUE TITLE
Chum submission

### ISSUE THREAD

**Issue by rinigus** [mjebdev/harbour-seachest#2]
I have accepted your submission to Chum, thank you for your interest.

However, please fix the following:

- specify license in RPM SPEC
- fix revision at OBS _service file (you can rw in chum:testing) - https://build.sailfishos.org/package/show/sailfishos:chum:testing/harbour-seachest

**Comment by mjebdev** [comment]
Thanks for this, I've updated the RPM SPEC and have made changes to the _service file. While the quaycentral edit seems to have gone through okay, this one may not have. I got an error when viewing the page for the package after saving '_service':

Files could not be expanded: service error: ERROR: couldn't checkout revision v0.2 

(Apologies if you get this twice, I replied to the email thinking GH would automatically put it here.)

**Comment by rinigus** [comment]
Here you go, fixed it at OBS. Note that you have no tags defined in Github - hence the issue. I suggest to use stripped down simpler _service as I made for you at OBS. That one has just commit ID and it works perfectly.

Thank you again for working on it and releasing via Chum!
